# Generated by Django 5.2.8 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_group_coach_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feet',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tall',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
