# Generated by Django 5.2.8 on 2025-11-11 11:52

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_feet_player_tall_player_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerevaluation',
            name='evaluated_at',
            field=models.DateField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerevaluation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.player'),
        ),
    ]
