# Generated by Django 5.2.8 on 2025-11-11 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_playerevaluation_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerevaluation',
            name='evaluated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
